const DUMMY_FINDINGS = [
  {
    id: "F001-1",
    title: "Ketidakselarasan Strategic Plan 2022-2027 dengan Program & RKAT — Program Loyalty Premium dan Program Member Growth Belum Tercantum di RKAT",
    rating: "high",
    status: "open",
    domain: "governance",
    fcaArea: "governance",
    lod: "first_line",
    cosoComponents: ["risk_assessment", "info_communication"],
    riskCategories: ["strategis", "operasional", "kepatuhan"],
    createdDate: "2024-12-10",
    condition: "Reviu atas Strategic Plan 2022-2027 dan dokumen RKAT 2024 menemukan:\n1) 'Program Loyalty Premium' dan 'Program Member Growth' yang merupakan inisiatif strategis dalam Strategic Plan Pasal 12 ayat (3) tidak tercantum dalam RKAT 2024\n2) KPI Balanced Scorecard untuk kedua program tersebut belum di-set, sehingga pencapaian tidak ter-track\n3) Anggaran operasional kedua program di-alokasikan informal melalui reklasifikasi pos lain (tidak transparent)\n4) Tidak ada Strategic Plan–RKAT–KPI Traceability Matrix yang formal\n5) Sample 18 KPI yang ada: 8 (44%) tidak terkait langsung dengan strategic objective di Strategic Plan",
    criteria: "Strategic Plan 2022-2027 Pasal 12 ayat (3) tentang Program Strategic; PP No.8/2006 tentang Pelaporan Keuangan & Kinerja Instansi; KNKG GCG Guidelines Pasal 3.2 (Akuntabilitas); COSO 2013 Principle 7 (Identifies and Analyzes Risks); IIA Standard 2120 (Risk Management); Balanced Scorecard methodology (Kaplan & Norton)",
    cause: "1) Process flow Strategic Plan → RKAT → KPI belum memiliki systematic linkage matrix dengan ownership per tier\n2) Tim Perencanaan understaffed (rasio 1:8 program, ideal 1:4)\n3) RKAT preparation cycle belum mengintegrasikan strategic review formal\n4) Tidak ada PMO/Strategy Office yang dedicated untuk Strategic Plan execution monitoring\n5) Cultural disconnect antara fungsi planning dan operational",
    effect: "1) Disconnect strategi-eksekusi → potential underperformance Strategic Plan objectives 30-40%\n2) Risiko anggaran inefisien — alokasi informal Rp2-5 miliar tidak transparent\n3) Pelanggaran prinsip akuntabilitas GCG — potensi temuan BPK/auditor eksternal\n4) Stakeholder confidence menurun karena strategic execution gap\n5) Kompetitif disadvantage — kompetitor sudah implement program serupa lebih dulu",
    recommendation: "1) Develop Strategic Plan–RKAT–KPI Traceability Matrix dengan PIC per program (target Q1 2025)\n2) Mandatory inclusion semua program strategis Strategic Plan dalam RKAT — no exception\n3) Establish KPI Balanced Scorecard untuk Program Loyalty Premium dan Program Member Growth dalam 60 hari\n4) Bentuk Strategy Management Office (SMO) atau PMO Function — minimal 2 staf dedicated\n5) Implementasi Quarterly Strategic Review dengan BoD untuk monitor execution\n6) Update Strategic Plan preparation cycle untuk include strategic-operational integration check",
    managementResponse: "Setuju. Strategy Management Office sudah dimasukkan dalam usulan struktur 2025. Traceability matrix akan dikembangkan dengan support konsultan eksternal. Target operasional Q2 2025.",
    targetDate: "2025-06-30",
    pic: "Direktur Perencanaan Strategis & Direktur Keuangan",
  },
  {
    id: "F001-2",
    title: "SOP Hanya Mencakup Proses Administrasi — Belum Mengatur Prosedur Tata Laksana Program",
    rating: "medium",
    status: "open",
    domain: "operations",
    fcaArea: "governance",
    lod: "first_line",
    cosoComponents: ["control_activities", "info_communication"],
    riskCategories: ["operasional", "kepatuhan"],
    createdDate: "2024-12-10",
    condition: "Pengujian atas 47 SOP yang berlaku di organisasi:\n1) 38 SOP (81%) hanya mengatur proses administrasi (registrasi, pencatatan, archiving)\n2) Hanya 9 SOP (19%) yang mencakup prosedur tata laksana program (pelaksanaan, monitoring, evaluasi)\n3) Tidak ada SOP untuk Program Loyalty Premium dan Program Member Growth\n4) SOP untuk event tahunan tidak mencakup procurement sponsorship dan accountability\n5) Last review SOP 2022 — belum di-update sejak Strategic Plan 2022-2027 ditetapkan\n6) Sample 30 transaksi: 11 (37%) dilaksanakan tanpa SOP yang spesifik",
    criteria: "ISO 9001:2015 Quality Management — Klausul 4.4 (Process Approach); COSO 2013 Principle 12 (Deploys Through Policies and Procedures); Pedoman Internal Pengembangan SOP No.PED-OPS-001/2021; IIA Standard 2210 (Engagement Objectives)",
    cause: "1) SOP development capability di-fokus ke compliance administratif, belum operational excellence\n2) Tidak ada SOP Officer atau Process Excellence team yang dedicated\n3) Belum ada review cycle reguler untuk SOP (recommended: setiap 2 tahun)\n4) Cultural — pegawai cenderung 'tahu by experience' tanpa formalisasi\n5) Knowledge transfer dari senior ke junior staf tidak ter-formal",
    effect: "1) Inconsistency dalam pelaksanaan program → hasil tidak repeatable\n2) Risiko operational dari rangkap fungsi atau gap responsibility\n3) Onboarding pegawai baru lebih lambat — dependency pada knowledge senior\n4) Audit trail lemah → temuan auditor eksternal dan potensi pelanggaran regulasi sektor\n5) Knowledge loss saat staf resign atau pensiun",
    recommendation: "1) Lakukan SOP Gap Analysis comprehensive (target 60 hari) — list mana yang perlu update/baru\n2) Develop SOP untuk Program Loyalty Premium, Member Growth, dan Event Tahunan dengan format end-to-end (admin + tata laksana)\n3) Tetapkan SOP review cycle: minor update annual, major review 2 tahun\n4) Bentuk Process Excellence team atau assign SOP Officer (minimal 1 senior)\n5) Implementasi SOP Management System digital (SharePoint/Confluence/Notion based)\n6) Training mandatory tata laksana program untuk semua PIC operasional",
    managementResponse: "Setuju. SOP Gap Analysis akan dilakukan Januari 2025. Process Excellence team akan dievaluasi dalam reorganisasi struktur 2025.",
    targetDate: "2025-09-30",
    pic: "Direktur Operasional & Sekretaris Perusahaan",
  },
  {
    id: "F001-3",
    title: "Pertanggungjawaban Event Tahunan Belum Mencakup Dana Non-RKAT — Sponsorship Rp1,25 Miliar Tidak Tercatat",
    rating: "high",
    status: "open",
    domain: "finance",
    fcaArea: "governance",
    lod: "first_line",
    cosoComponents: ["control_activities", "info_communication", "monitoring"],
    riskCategories: ["keuangan", "kepatuhan", "reputasi", "hukum"],
    createdDate: "2024-12-10",
    condition: "Reviu atas pertanggungjawaban Event Tahunan 'Anniversary Gala 2024':\n1) Dana sponsorship dari 7 mitra sebesar Rp1,25 miliar TIDAK tercatat dalam laporan pertanggungjawaban formal\n2) Dana digunakan untuk pengadaan: katering Rp380jt, dekorasi Rp280jt, talent fee Rp420jt, lain-lain Rp170jt — tanpa SPK formal\n3) 3 dari 7 vendor sponsorship tidak memiliki PKS (Perjanjian Kerja Sama) tertulis\n4) Tidak ada audit trail untuk reconciliation antara dana masuk dan pengeluaran\n5) Bukti pengeluaran berupa bon-bon sederhana (Rp680jt) — tidak melalui purchase order formal\n6) Pajak penghasilan (PPh) atas dana sponsorship belum di-setor — potensi denda Rp187jt\n7) Tidak ada laporan keuangan terpisah untuk event tahunan — hanya summary memo internal",
    criteria: "PP No.8/2006 tentang Pelaporan Keuangan; UU No.36/2008 tentang Pajak Penghasilan; PSAK 23 (Pendapatan); KNKG GCG Guidelines — Akuntabilitas; ISO 37001:2016 Anti-Bribery Management Systems (untuk sponsorship); Pedoman Pengelolaan Dana Non-RKAT (jika ada)",
    cause: "1) Tidak ada Pedoman Pengelolaan Dana Non-RKAT yang formal\n2) Treasurer/PIC event mengelola dana di-luar sistem akuntansi formal\n3) Tidak ada kewajiban formal melaporkan dana sponsorship ke Bidang Keuangan\n4) Cultural — event committee menganggap dana sponsorship 'ekstra' di-luar mainstream\n5) Lemahnya internal control — tidak ada maker-checker untuk pengeluaran\n6) Ketidaktahuan tax obligation untuk sponsorship",
    effect: "1) Risiko denda pajak Rp187jt + bunga + sanksi administratif\n2) Pelanggaran serius prinsip GCG akuntabilitas dan transparansi\n3) Risiko reputasi jika kasus muncul di publik (suspect of bribery atau illicit funds)\n4) Pelanggaran ISO 37001 anti-bribery jika diaudit\n5) Personal liability untuk direksi dan committee members\n6) Audit eksternal qualified opinion risk\n7) Risiko hukum: pidana UU Tipikor jika ditemukan benefit personal\n8) Loss of trust dari mitra sponsorship untuk event berikutnya",
    recommendation: "1) URGENT: Lakukan investigasi forensic atas Rp1,25 miliar dalam 30 hari — verifikasi semua pengeluaran legitimate\n2) Setor pajak PPh sponsorship + denda dalam 14 hari untuk minimize sanksi\n3) Develop Pedoman Pengelolaan Dana Non-RKAT formal (target 60 hari)\n4) Mandatory: semua dana sponsorship tercatat di sistem akuntansi formal — no off-book\n5) Implementasi maker-checker untuk semua pengeluaran event ≥Rp10jt\n6) Wajibkan PKS tertulis dengan klausul akuntabilitas untuk semua sponsorship\n7) Quarterly reporting event accountability ke Komite Audit\n8) Training tax compliance untuk Treasurer dan event PIC\n9) Pertimbangkan engage forensic auditor eksternal untuk independent assurance",
    managementResponse: "Sangat setuju ini critical. Tim investigasi internal sudah dibentuk. Konsultan forensic akan engaged untuk independent review. Pedoman Pengelolaan Dana Non-RKAT akan diprioritaskan untuk Q1 2025.",
    targetDate: "2025-03-31",
    pic: "Direktur Keuangan & Sekretaris Perusahaan",
  },
  {
    id: "F001-4",
    title: "Tugas Pengelolaan Data Nasabah Belum Dimuat dalam SOTK — Gap Job Description & Akuntabilitas Pelindungan Data",
    rating: "medium",
    status: "open",
    domain: "it_security",
    fcaArea: "governance",
    lod: "first_line",
    cosoComponents: ["control_environment", "control_activities"],
    riskCategories: ["operasional", "kepatuhan", "hukum"],
    createdDate: "2024-12-10",
    condition: "Reviu atas Struktur Organisasi & Tata Kerja (SOTK) terkini:\n1) SOTK tidak memuat tugas pengelolaan data nasabah (estimasi 47.000+ records)\n2) Tidak ada Data Protection Officer (DPO) atau function setara — wajib per UU 27/2022 PDP untuk organisasi dengan data >10.000 subjek\n3) PIC pengelolaan data nasabah secara de-facto adalah 4 staf di berbagai unit, namun tidak formal di-assign\n4) Job description 4 staf tersebut tidak mencakup data protection responsibility\n5) Tidak ada formal training Data Protection untuk staf pengelola data\n6) Bidang IT menangani aspek teknis, namun governance data protection belum ditugaskan ke fungsi spesifik\n7) Data classification policy belum ada (PII, sensitive data, public data)\n8) Last SOTK update: 2022 — sebelum UU PDP berlaku efektif",
    criteria: "UU No.27/2022 tentang Pelindungan Data Pribadi (PDP) — Pasal 53-55 (DPO requirement); ISO/IEC 27701:2019 Privacy Information Management; KNKG GCG Guidelines — Lingkungan Pengendalian; COSO 2013 Principle 3 (Establishes Structure, Authority, and Responsibility); Permenkominfo PDP implementing regulations",
    cause: "1) SOTK update lag — belum keep up dengan regulatory landscape (UU PDP)\n2) Awareness rendah tentang DPO requirement di level senior management\n3) Process organizational change management belum incorporate regulatory updates\n4) Bidang HR tidak track regulatory changes yang impact organizational structure\n5) Tidak ada periodic review SOTK (recommended: annual)\n6) Resource constraint — DPO requires senior level dengan kompetensi spesifik",
    effect: "1) Pelanggaran UU PDP — denda KPDP potensial Rp1-50 miliar (UU PDP Pasal 57)\n2) Risiko personal liability untuk Direksi (UU PDP memungkinkan personal sanction)\n3) Data breach risk meningkat tanpa governance jelas\n4) Reputational damage jika ada insiden privacy\n5) Vendor/mitra concern tentang data sharing agreements\n6) Kompetitif disadvantage — kompetitor sudah compliant\n7) Gap dalam internal control — accountability tidak jelas saat insiden",
    recommendation: "1) URGENT: Update SOTK untuk memasukkan tugas pengelolaan data nasabah (target 90 hari)\n2) Recruit atau assign Data Protection Officer (DPO) — minimal level Senior Manager\n3) Tetapkan formal PIC untuk pengelolaan data nasabah dengan job description spesifik\n4) Develop Data Protection Policy & Data Classification Standard\n5) Mandatory training UU PDP untuk semua staf pengelola data (min. 16 jam/tahun)\n6) Implementasi annual SOTK review dengan focus on regulatory alignment\n7) Establish Privacy Impact Assessment (PIA) framework untuk program/sistem baru\n8) Lakukan PDP Compliance Self-Assessment dalam 60 hari\n9) Coordinate dengan Bidang Hukum untuk privacy notice update",
    managementResponse: "Setuju. Recruitment DPO sudah dimasukkan dalam Manpower Planning 2025. SOTK update akan diprioritaskan Q1 2025. Konsultan PDP akan engaged untuk gap assessment.",
    targetDate: "2025-06-30",
    pic: "Direktur SDM & Direktur Hukum/Kepatuhan",
  },
];

const DEFAULT_STATE = {
  activeTab: "dashboard",
  aiConfig: { provider: "groq", apiKey: "", customEndpoint: "", customModel: "" },
  auditInfo: {
    title: "Audit Tata Kelola Strategis & Akuntabilitas Program 2024",
    number: "001/LHA/AI/12/2024",
    date: "2024-12-15",
    period: "Januari 2024 - November 2024",
    rating: "cukup_efektif",
    unit: "Bidang Perencanaan Strategis & Operasional",
    org: "PT Mitra Sejahtera Nusantara — Mockup",
    objective: "Menilai keselarasan Strategic Plan 2022-2027 dengan program/RKAT/KPI Balanced Scorecard, kelengkapan SOP tata laksana, akuntabilitas event tahunan, dan kesesuaian SOTK dengan tugas-tugas operasional terkini",
    auditScope: "Strategic Planning, Program Management, Event Management, SOTK & Job Description",
  },
  team: [
    { role: "Penanggung Jawab", name: "Drs. Ahmad Fauzan, M.Ak., CIA, CRMA" },
    { role: "Pengendali Teknis", name: "Ratna Dewi Sari, SE., M.M., CIA" },
    { role: "Ketua Tim", name: "Budi Santoso, S.Kom., M.M., QIA, CISA" },
    { role: "Anggota Tim", name: "Siti Nurhaliza, SE., CFE" },
    { role: "Anggota Tim", name: "Dian Permata Sari, S.Ak., CCSA" },
  ],
  cosoAssessment: {
    control_environment: { rating: "perlu_perbaikan", notes: "SOTK belum mengakomodasi tugas pengelolaan data nasabah. Job description belum di-update sejak 2022 padahal ada perubahan portfolio program." },
    risk_assessment: { rating: "perlu_perbaikan", notes: "Linkage antara Strategic Plan–RKAT–KPI belum systematic. Strategic risks dari program baru (tabungan, cicilan setoran lunas) belum di-RCSA." },
    control_activities: { rating: "perlu_perbaikan", notes: "SOP fokus pada proses administrasi, belum cover tata laksana program. Maker-checker untuk dana non-RKAT belum formal." },
    info_communication: { rating: "perlu_perbaikan", notes: "Pelaporan accountability dana sponsorship Rp1,25M tidak tercatat. Komunikasi linkage strategi → operasional masih ad-hoc." },
    monitoring: { rating: "perlu_perbaikan", notes: "Strategic Plan Annual Review tidak dilakukan formal. KPI tracking KPI Balanced Scorecard untuk program baru belum established." },
  },
  findings: DUMMY_FINDINGS,
  observations: [
    { id: "O001", title: "Strategic Plan Annual Review Tidak Dilakukan Secara Formal Sejak 2022", notes: "Strategic Plan 2022-2027 ditetapkan tanpa annual review formal. Disarankan implementasi Quarterly Strategic Review (QSR) dengan BoD untuk monitor execution dan respond ke perubahan environment. Best practice: McKinsey Strategy Refresh framework atau OKR methodology untuk dynamic strategy execution." },
    { id: "O002", title: "KPI Balanced Scorecard Belum Cascade ke Level Individual", notes: "Sample 12 staf operasional: 8 (67%) tidak memiliki KPI individual yang link ke KPI unit dan KPI strategis. Disarankan implementasi BSC cascade end-to-end dari corporate → unit → individual untuk strengthen line-of-sight execution." },
    { id: "O003", title: "Strategy-Operations Integration Forum Belum Ada", notes: "Tidak ada reguler forum yang menyatukan tim Perencanaan dan tim Operasional untuk discuss strategic alignment. Disarankan monthly Strategy-Operations Review meeting dengan agenda: progress KPI, emerging risks, resource reallocation." },
    { id: "O004", title: "Vendor Sponsorship Database Belum Ter-konsolidasi", notes: "Mitra sponsorship event tahunan tersebar di Excel berbagai unit, tidak terkonsolidasi. Disarankan develop Vendor Sponsorship Master Database dengan tracking: cumulative value, conflict of interest check, multi-year relationship analysis." },
    { id: "O005", title: "Knowledge Management System untuk SOP Belum Mature", notes: "SOP saat ini di-manage via shared folder tanpa version control yang strict. Disarankan implementasi digital SOP Management System (Confluence, Notion, atau Lucidchart) dengan version control, approval workflow, dan search capability." },
  ],
  auditTimeline: [
    { date: "2024-09-01", event: "Surat Tugas Audit Diterbitkan", type: "milestone" },
    { date: "2024-09-05", event: "Entry Meeting dengan Manajemen", type: "meeting" },
    { date: "2024-09-15", event: "Field Work Phase 1 — Strategic Planning Review", type: "fieldwork" },
    { date: "2024-10-10", event: "Field Work Phase 2 — Event Accountability Review", type: "fieldwork" },
    { date: "2024-11-05", event: "Field Work Phase 3 — SOTK & Data Governance", type: "fieldwork" },
    { date: "2024-11-20", event: "Konsep Temuan Disampaikan ke Manajemen", type: "draft" },
    { date: "2024-12-05", event: "Tanggapan Manajemen Diterima", type: "response" },
    { date: "2024-12-12", event: "Exit Meeting", type: "meeting" },
    { date: "2024-12-15", event: "Laporan Hasil Audit Final Diterbitkan", type: "milestone" },
  ],
};

export default DEFAULT_STATE;
