const DUMMY_FINDINGS = [
  {
    id: "F001",
    title: "Kelemahan Segregation of Duties pada Proses Pengadaan Barang & Jasa",
    rating: "high",
    cosoComponents: ["control_activities", "control_environment"],
    riskCategories: ["operasional", "kepatuhan", "reputasi"],
    domain: "procurement",
    condition: "Hasil pengujian terhadap 45 transaksi pengadaan periode Q1-Q3 2024 menemukan:\n1) 12 transaksi (26,7%) di mana fungsi inisiator, verifikator, dan approver dilakukan oleh satu orang yang sama\n2) 7 transaksi senilai total Rp4,2 miliar tidak melalui proses tender meskipun di atas threshold Rp500 juta\n3) Vendor master database mengandung 23 vendor duplikat dengan NPWP yang sama namun nama berbeda",
    criteria: "Pedoman Pengadaan Internal No.PED-PRC-001/2023 Pasal 12 (Pemisahan Fungsi); Peraturan Menteri Keuangan tentang Pengadaan Barang/Jasa; COSO 2013 Principle 10 (Selects and Develops Control Activities)",
    cause: "1) Pembatasan SDM di unit pengadaan menyebabkan rangkap fungsi\n2) Sistem ERP belum dikonfigurasi untuk segregation of duties (SoD) matrix\n3) Proses pengkinian vendor master belum terdapat mekanisme deduplikasi otomatis\n4) Belum ada threshold-based escalation matrix yang ter-otomasi",
    effect: "1) Risiko fraud meningkat secara signifikan — potensi kerugian estimasi Rp600 juta - Rp1,2 miliar berdasarkan ACFE Report to the Nations\n2) Pelanggaran terhadap prinsip GCG terutama akuntabilitas\n3) Risiko temuan eksternal auditor (BPK/KAP) yang dapat menurunkan opini audit\n4) Reputasi organisasi di mata stakeholder",
    recommendation: "1) Konfigurasi ERP untuk enforce SoD matrix dengan workflow approval bertingkat (target Q1 2025)\n2) Recruit minimal 2 staf tambahan di unit pengadaan untuk eliminasi rangkap fungsi\n3) Implementasi vendor master cleansing dan deduplication dengan validasi NPWP via DJP API\n4) Tetapkan threshold-based escalation: <Rp100jt (Manager), Rp100-500jt (Senior Manager), >Rp500jt (Direktur via tender)",
    managementResponse: "Setuju. Pengadaan ERP enhancement sudah dimasukkan ke RKAT 2025. Recruitment SDM akan diproses melalui Bidang SDM. Vendor cleansing target selesai Q2 2025.",
    targetDate: "2025-06-30",
    pic: "Direktur Operasional & Kepala Unit Pengadaan",
    status: "in_progress",
    createdDate: "2024-11-15",
  },
  {
    id: "F002",
    title: "Akses User Dormant Belum Dinonaktifkan pada Sistem Aplikasi Core",
    rating: "high",
    cosoComponents: ["control_activities", "info_communication"],
    riskCategories: ["operasional", "kepatuhan"],
    domain: "it_security",
    condition: "Pengujian atas 1.247 user account aktif di sistem core banking menunjukkan:\n1) 187 akun (15%) tidak memiliki aktivitas login >90 hari\n2) 43 akun masih aktif dari pegawai yang sudah resign sejak 6-18 bulan lalu\n3) 12 akun memiliki privilege admin tanpa periodic review yang terdokumentasi\n4) Tidak ada automated alert untuk dormant accounts atau privileged access reviews",
    criteria: "Kebijakan Keamanan TI No.POL-IT-005/2022; ISO/IEC 27001:2022 Control A.5.16 (Identity Management); COBIT 2019 DSS05 (Managed Security Services); UU 27/2022 Pelindungan Data Pribadi",
    cause: "1) Proses offboarding belum terintegrasi end-to-end antara HR dan IT\n2) Tidak ada automated provisioning/de-provisioning workflow\n3) IAM tools tidak memiliki dormancy detection capability\n4) Belum ada periodic access review yang ter-jadwal",
    effect: "1) Risiko unauthorized access dan data breach — potensi denda PDP Rp2-50 miliar\n2) Pelanggaran principle of least privilege\n3) Audit trail menjadi kurang reliable\n4) Potensi insider threat dari ex-employee accounts",
    recommendation: "1) Implementasi IAM solution dengan automated dormancy detection (target Q2 2025)\n2) Buat SOP offboarding terintegrasi HR-IT dengan SLA <24 jam\n3) Lakukan emergency disable untuk 43 akun ex-employee dalam 7 hari\n4) Tetapkan periodic access review setiap 90 hari untuk privileged accounts\n5) Konfigurasi SIEM untuk alerting pada dormant account activation",
    managementResponse: "Akan segera memproses disable 43 akun ex-employee. Project IAM modernization sudah dianggarkan. Target full implementation Q3 2025.",
    targetDate: "2025-09-30",
    pic: "Direktur Teknologi Informasi",
    status: "in_progress",
    createdDate: "2024-12-03",
  },
  {
    id: "F003",
    title: "Rekonsiliasi Bank Bulanan Belum Dilakukan Tepat Waktu",
    rating: "medium",
    cosoComponents: ["control_activities", "monitoring"],
    riskCategories: ["operasional", "keuangan"],
    domain: "finance",
    condition: "Reviu atas rekonsiliasi bank periode Januari-September 2024 untuk 8 rekening operasional menemukan:\n1) Rekonsiliasi rata-rata baru selesai 18 hari setelah cut-off (target: 5 hari)\n2) 23 outstanding items berusia >60 hari belum di-clear (total nilai Rp187 juta)\n3) 4 selisih rekonsiliasi berulang setiap bulan namun belum diinvestigasi tuntas\n4) Tidak ada dual-review untuk rekonsiliasi di atas Rp1 miliar",
    criteria: "SOP Rekonsiliasi No.SOP-FIN-012; PSAK 71 (Instrumen Keuangan); Praktik Industri 5-day close",
    cause: "1) Volume transaksi meningkat 35% YoY tanpa penambahan SDM finance\n2) Tools rekonsiliasi masih manual menggunakan Excel\n3) Bank statement format tidak terstandar antar 8 bank\n4) Tidak ada KPI individual untuk timeliness rekonsiliasi",
    effect: "1) Laporan keuangan bulanan tertunda dan tidak reliable untuk decision-making\n2) Outstanding items berisiko menjadi unrecoverable\n3) Potensi misstatement pada laporan keuangan tahunan\n4) Audit external memerlukan waktu lebih panjang",
    recommendation: "1) Implementasi automated reconciliation tool (BlackLine/SAP) — ROI < 18 bulan\n2) Integrasi host-to-host dengan 8 bank untuk real-time statement feed\n3) Investigasi & clearance 23 outstanding items dalam 60 hari\n4) Tetapkan KPI individual: rekonsiliasi selesai T+5\n5) Implementasi maker-checker untuk rekonsiliasi >Rp1M",
    managementResponse: "Setuju automation tool. Sedang evaluasi vendor. Outstanding items akan di-clear dengan task force.",
    targetDate: "2025-05-31",
    pic: "Direktur Keuangan",
    status: "open",
    createdDate: "2024-10-20",
  },
  {
    id: "F004",
    title: "Whistleblowing System Belum Sepenuhnya Independen dan Anonim",
    rating: "medium",
    cosoComponents: ["control_environment", "info_communication"],
    riskCategories: ["kepatuhan", "reputasi"],
    domain: "compliance",
    condition: "Evaluasi terhadap WBS organisasi periode 2023-2024:\n1) Channel pelaporan dikelola oleh internal staff (Bidang Kepatuhan), bukan independent third party\n2) Hanya 7 laporan masuk dalam 24 bulan terakhir (industry benchmark: 1-2 laporan per 100 karyawan/tahun)\n3) Tidak ada survey persepsi karyawan tentang trust pada WBS\n4) Belum ada perlindungan formal untuk whistleblower (no anti-retaliation policy)\n5) Reporting channel hanya via email, tidak ada hotline/portal anonymous",
    criteria: "ISO 37002:2021 Whistleblowing Management Systems; UU 31/1999 jo 20/2001 Tipikor; Peraturan KNKG tentang WBS Guidelines; OJK POJK No.39 untuk lembaga keuangan",
    cause: "1) Belum ada komitmen manajemen untuk outsource ke independent provider\n2) Anggaran WBS yang terbatas (Rp45 juta/tahun)\n3) Awareness karyawan rendah karena kurangnya socialization campaign\n4) Tidak ada KPI kepatuhan untuk WBS effectiveness",
    effect: "1) Underreporting fraud/misconduct — fraud bisa berlangsung lebih lama tanpa terdeteksi\n2) Pelanggaran prinsip GCG terutama transparency\n3) Tidak compliant dengan ISO 37002 jika ingin certified\n4) Risiko reputasi jika kasus muncul ke publik via channel eksternal",
    recommendation: "1) Outsource WBS ke independent provider (estimasi Rp150-300 juta/tahun)\n2) Implementasi multi-channel: hotline 24/7, web portal anonymous, mobile app\n3) Tetapkan formal anti-retaliation policy yang ditandatangani BoD\n4) Lakukan WBS awareness campaign berkelanjutan (quarterly)\n5) Tambah KPI: minimum 1 laporan per 200 karyawan/tahun",
    managementResponse: "Akan dievaluasi dalam RKAT 2025. Anti-retaliation policy akan diprioritaskan untuk Q1 2025.",
    targetDate: "2025-12-31",
    pic: "Direktur Kepatuhan & Hukum",
    status: "open",
    createdDate: "2024-09-12",
  },
  {
    id: "F005",
    title: "Business Continuity Plan (BCP) Belum Diuji Sejak 2022",
    rating: "high",
    cosoComponents: ["risk_assessment", "monitoring"],
    riskCategories: ["operasional", "strategis", "reputasi"],
    domain: "bcp_drm",
    condition: "Reviu atas dokumentasi BCP dan DRP organisasi:\n1) Last BCP test dilakukan 14 Februari 2022 (>30 bulan tanpa test)\n2) BCP document last updated 2021 — tidak mencerminkan perubahan struktur organisasi 2023-2024\n3) RTO/RPO untuk sistem kritis belum di-define secara formal\n4) DR site secondary belum pernah diaktifkan (cold standby)\n5) Tidak ada training BCP untuk anggota tim baru sejak 2022",
    criteria: "ISO 22301:2019 Business Continuity Management; Peraturan Bank Indonesia/OJK terkait BCM untuk lembaga keuangan; Best practice tahunan BCP testing",
    cause: "1) Anggapan bahwa BCP testing 'mengganggu operasional'\n2) Tidak ada BCM Officer dedicated\n3) Belum ada governance forum khusus BCP (BCM Steering Committee)\n4) Anggaran BCP testing belum dialokasikan",
    effect: "1) Kemampuan recovery saat disaster TIDAK TERVERIFIKASI — risiko downtime ekstrem\n2) Estimasi loss saat disaster: Rp2-5 miliar/hari downtime untuk core operations\n3) Pelanggaran regulasi sektor (jika lembaga keuangan)\n4) Tidak compliant ISO 22301",
    recommendation: "1) Lakukan BCP tabletop exercise dalam 30 hari (tanpa biaya signifikan)\n2) Lakukan full BCP test (failover ke DR site) dalam 90 hari\n3) Update BCP documentation dengan struktur organisasi terkini\n4) Tetapkan RTO/RPO formal per sistem kritis\n5) Bentuk BCM Steering Committee dengan executive sponsor\n6) Schedule annual BCP testing dengan reporting ke BoD",
    managementResponse: "Setuju ini high priority. BCP tabletop akan dijadwalkan Februari 2025. Full test target Q2 2025.",
    targetDate: "2025-06-30",
    pic: "Direktur Risiko & Direktur Teknologi Informasi",
    status: "open",
    createdDate: "2024-12-10",
  },
  {
    id: "F006",
    title: "Penatausahaan Aset Tetap Belum Mencerminkan Kondisi Sebenarnya",
    rating: "medium",
    cosoComponents: ["control_activities", "monitoring"],
    riskCategories: ["operasional", "keuangan"],
    domain: "asset_management",
    condition: "Stock opname aset tetap per November 2024 atas sample 350 aset dengan total nilai Rp45 miliar:\n1) 47 aset (13,4%) tidak ditemukan di lokasi yang tercatat\n2) 28 aset ditemukan di lokasi berbeda dari catatan tanpa dokumen mutasi\n3) 15 aset dalam kondisi rusak berat namun masih dicatat sebagai aktif\n4) Selisih nilai antara catatan akuntansi dan fisik: Rp1,8 miliar (4%)\n5) 6 aset tidak memiliki barcode/asset tag",
    criteria: "PSAK 16 Aset Tetap; SOP Penatausahaan Aset No.SOP-ASS-008; Kebijakan internal stock opname tahunan",
    cause: "1) Mutasi aset antar unit tidak konsisten didokumentasikan\n2) Tidak ada sistem asset tracking real-time (RFID/barcode scanner)\n3) Stock opname hanya dilakukan tahunan, bukan rolling/cycle counting\n4) Kategorisasi aset rusak/aktif belum jelas dalam SOP",
    effect: "1) Misstatement pada Laporan Posisi Keuangan untuk akun Aset Tetap\n2) Risiko temuan auditor eksternal dengan dampak ke opini\n3) Potensi kehilangan/pencurian aset tidak terdeteksi tepat waktu\n4) Inefisiensi: aset yang ada tidak dimanfaatkan karena tidak ditemukan",
    recommendation: "1) Implementasi asset tracking system dengan QR code/RFID (target Q3 2025)\n2) Lakukan full stock opname rekonsiliasi dalam 60 hari untuk membersihkan catatan\n3) Tetapkan SOP cycle counting bulanan untuk 10% aset rotasi\n4) Penyelidikan dan pertanggungjawaban untuk 47 aset hilang\n5) Tetapkan formal write-off policy untuk aset rusak berat",
    managementResponse: "Setuju. Asset tracking system akan dievaluasi. Stock opname rekonsiliasi akan dilakukan Januari 2025.",
    targetDate: "2025-09-30",
    pic: "Direktur Umum & Direktur Keuangan",
    status: "in_progress",
    createdDate: "2024-11-25",
  },
  {
    id: "F007",
    title: "Anti-Money Laundering Screening Belum Mencakup Sanction List Terkini",
    rating: "high",
    cosoComponents: ["control_activities", "info_communication", "risk_assessment"],
    riskCategories: ["kepatuhan", "reputasi", "hukum"],
    domain: "aml_compliance",
    condition: "Reviu atas AML screening process untuk customer onboarding & ongoing monitoring:\n1) Sanction list yang digunakan masih versi Q1 2024 — terlambat update 9 bulan\n2) Tidak terhubung dengan PPATK DTTOT real-time, masih batch update bulanan\n3) Adverse media screening belum terimplementasi\n4) PEP (Politically Exposed Person) database belum ter-integrasi\n5) Sample 200 transaksi: 8 transaksi (4%) menunjukkan red flag namun tidak di-escalate ke compliance",
    criteria: "UU 8/2010 Pencegahan & Pemberantasan TPPU; Peraturan PPATK 11/2016; FATF Recommendations; UN Consolidated Sanctions List; OFAC SDN List",
    cause: "1) Vendor AML screening tool yang digunakan tidak include real-time updates\n2) Kontrak dengan vendor sanction list provider expired\n3) Compliance team kekurangan SDM (rasio 1:5000 nasabah, ideal 1:2000)\n4) Tidak ada AML Risk Assessment formal yang ter-update",
    effect: "1) Risiko transaksi dengan sanctioned parties — denda potensi Rp10 miliar+ dari PPATK/OJK\n2) Risiko reputasi — kasus AML/CFT yang viral di media\n3) Pelanggaran kewajiban CDD/EDD\n4) Pidana untuk Direksi (max 15 tahun + denda Rp10 miliar UU TPPU)",
    recommendation: "1) URGENT: Update sanction list dan integrate dengan PPATK DTTOT API dalam 30 hari\n2) Renew kontrak vendor AML screening dengan SLA real-time updates\n3) Implementasi adverse media & PEP screening (target Q1 2025)\n4) Recruit 3 compliance analyst tambahan\n5) Lakukan AML Risk Assessment formal & RBA approach\n6) Investigasi 8 transaksi red flag dan dokumentasikan SAR jika diperlukan",
    managementResponse: "Sangat setuju ini critical. Emergency procurement untuk update vendor sudah dimulai. Tim investigation untuk 8 transaksi red flag sudah dibentuk.",
    targetDate: "2025-03-31",
    pic: "Direktur Kepatuhan / MLRO",
    status: "in_progress",
    createdDate: "2024-12-18",
  },
  {
    id: "F008",
    title: "Kebijakan Conflict of Interest (CoI) Disclosure Belum Implementatif",
    rating: "low",
    cosoComponents: ["control_environment"],
    riskCategories: ["kepatuhan", "reputasi"],
    domain: "governance",
    condition: "Reviu atas implementasi CoI policy:\n1) Policy ada (No.POL-GCG-003/2021) namun belum di-update sejak 2021\n2) Annual disclosure form hanya diisi 67% pegawai (target: 100%)\n3) Tidak ada digital tracking untuk disclosure\n4) Tidak ada CoI committee untuk evaluasi disclosure yang material\n5) Sample 30 disclosure: 12 (40%) form tidak lengkap atau hanya tanda tangan tanpa pengisian substantif",
    criteria: "PBPKH atau peraturan internal tentang Kode Etik & GCG; KNKG GCG Guidelines; ISO 37001 (untuk anti-bribery aspect)",
    cause: "1) Awareness yang rendah — pegawai menganggap formalitas\n2) Form disclosure manual paper-based\n3) Tidak ada sanksi untuk non-disclosure\n4) Tone-at-the-top kurang konsisten",
    effect: "1) Risiko CoI tidak terdeteksi sehingga keputusan bias\n2) Potensi conflict yang berdampak finansial dan reputasi\n3) Tidak compliant dengan best practice GCG",
    recommendation: "1) Update CoI policy dengan kategorisasi tegas (definite, perceived, potential)\n2) Implementasi digital CoI disclosure platform dengan annual reminder\n3) Bentuk CoI Committee (3 anggota independent)\n4) Lakukan CoI awareness training (mandatory e-learning)\n5) Tetapkan sanksi formal untuk non-disclosure\n6) Reporting CoI dashboard ke Komite Audit quarterly",
    managementResponse: "Akan dimasukkan ke roadmap GCG 2025. Digital platform akan dievaluasi.",
    targetDate: "2025-12-31",
    pic: "Direktur Kepatuhan & Sekretaris Perusahaan",
    status: "open",
    createdDate: "2024-08-30",
  },
];

const DEFAULT_STATE = {
  activeTab: "dashboard",
  aiConfig: { provider: "groq", apiKey: "", customEndpoint: "", customModel: "" },
  auditInfo: {
    title: "Audit Tata Kelola, Manajemen Risiko & Pengendalian Internal Tahun 2024",
    number: "DWN/LHA/AI/12/2024",
    date: "2024-12-20",
    period: "Januari 2024 - Desember 2024",
    rating: "cukup_efektif",
    unit: "Seluruh Bidang Operasional",
    org: "PT Mitra Sejahtera Nusantara (Tbk) — Mockup",
    objective: "Menilai efektivitas tata kelola, manajemen risiko, dan pengendalian internal pada operasional Perusahaan untuk memastikan pencapaian tujuan strategis, kepatuhan terhadap regulasi, dan integritas pelaporan",
    auditScope: "Pengadaan, IT Security, Keuangan, Kepatuhan, BCP, Asset Management, AML, dan Governance",
  },
  team: [
    { role: "Penanggung Jawab", name: "Drs. Ahmad Fauzan, M.Ak., CIA, CRMA" },
    { role: "Pengendali Teknis", name: "Ratna Dewi Sari, SE., M.M., CIA" },
    { role: "Ketua Tim", name: "Budi Santoso, S.Kom., M.M., QIA, CISA" },
    { role: "Anggota Tim", name: "Siti Nurhaliza, SE., CFE" },
    { role: "Anggota Tim", name: "Dian Permata Sari, S.Ak., CCSA" },
    { role: "Anggota Tim", name: "Reza Pratama, ST., M.T., CRISC" },
  ],
  cosoAssessment: {
    control_environment: { rating: "memadai", notes: "Tone at the top relatif baik, kode etik dan pakta integritas sudah ditandatangani. Namun CoI disclosure perlu penguatan implementasi." },
    risk_assessment: { rating: "perlu_perbaikan", notes: "ERM framework ada namun BCP risk belum di-assess komprehensif. RCSA dilakukan semesteran, belum mencakup emerging risks." },
    control_activities: { rating: "perlu_perbaikan", notes: "SoD violations di pengadaan, otomatisasi rekonsiliasi belum optimal, AML screening lag. Maker-checker generally implemented." },
    info_communication: { rating: "perlu_perbaikan", notes: "Pelaporan internal cukup memadai. Namun WBS masih internal-managed dan AML data lag 9 bulan. PDP compliance perlu attention." },
    monitoring: { rating: "perlu_perbaikan", notes: "BCP testing tidak dilakukan sejak 2022. Ongoing monitoring untuk dormant accounts dan asset tracking belum optimal." },
  },
  findings: DUMMY_FINDINGS,
  observations: [
    { id: "O001", title: "Customer satisfaction survey belum dilakukan secara konsisten", notes: "Last survey 2023 dengan response rate hanya 23%. Diperlukan strategi survey yang lebih engaging." },
    { id: "O002", title: "Training & development budget under-utilized 32%", notes: "Realisasi training Rp680 juta dari budget Rp1 miliar. Beberapa pelatihan strategis tidak terlaksana karena scheduling conflict." },
    { id: "O003", title: "Vendor performance evaluation belum sistematis", notes: "Hanya 18% vendor yang dievaluasi formal pada akhir kontrak. Perlu vendor scorecard standar." },
    { id: "O004", title: "ESG reporting belum mengikuti GRI Standards terbaru", notes: "Sustainability report 2023 masih mengacu GRI 2016. Update ke GRI 2021 disarankan untuk kredibilitas pelaporan." },
  ],
  auditTimeline: [
    { date: "2024-08-15", event: "Surat Tugas Audit Diterbitkan", type: "milestone" },
    { date: "2024-08-20", event: "Entry Meeting dengan Manajemen", type: "meeting" },
    { date: "2024-09-01", event: "Field Work Phase 1 — Procurement & Finance", type: "fieldwork" },
    { date: "2024-10-15", event: "Field Work Phase 2 — IT Security & BCP", type: "fieldwork" },
    { date: "2024-11-10", event: "Field Work Phase 3 — Compliance & Governance", type: "fieldwork" },
    { date: "2024-11-30", event: "Konsep Temuan Disampaikan ke Manajemen", type: "draft" },
    { date: "2024-12-10", event: "Tanggapan Manajemen Diterima", type: "response" },
    { date: "2024-12-15", event: "Exit Meeting", type: "meeting" },
    { date: "2024-12-20", event: "Laporan Hasil Audit Final Diterbitkan", type: "milestone" },
  ],
};

export default DEFAULT_STATE;
