const DEFAULT_STATE = {
  activeTab: "dashboard",
  auditInfo: {
    title: "Pengelolaan Program dan Kegiatan Penghimpunan Dana untuk Mendukung Peningkatan Dana Kelolaan",
    number: "XX/LHA/AI/MM/2025",
    date: "2025-08-19",
    period: "2023-2024",
    rating: "cukup_efektif",
    unit: "Bidang Penghimpunan Dana",
    org: "Lembaga Pengelola Dana Publik (LPDP) — Contoh Mockup",
    objective: "Menilai efektivitas tata kelola, manajemen risiko, dan pengendalian internal atas program dan kegiatan penghimpunan dana untuk mendukung peningkatan dana kelolaan",
  },
  team: [
    { role: "Penanggung Jawab", name: "Ahmad Fauzan, SE., M.Ak." },
    { role: "Pengendali Teknis", name: "Ratna Dewi, CIA" },
    { role: "Ketua Tim", name: "Budi Santoso, QIA" },
    { role: "Anggota Tim", name: "Siti Nurhaliza" },
    { role: "Anggota Tim", name: "Dian Permata Sari" },
  ],
  cosoAssessment: {
    control_environment: { rating: "memadai", notes: "Pakta integritas telah ditandatangani seluruh personil. SOTK telah ditetapkan namun perlu penyesuaian terkait pengelolaan data peserta." },
    risk_assessment: { rating: "perlu_perbaikan", notes: "RCSA dilakukan setiap semester. Profil risiko periode terakhir belum disusun. Komposit risiko mengalami kenaikan." },
    control_activities: { rating: "perlu_perbaikan", notes: "Maker-checker-approval telah diimplementasikan. Namun program/kegiatan belum seluruhnya dituangkan dalam prosedur tetap (SOP)." },
    info_communication: { rating: "perlu_perbaikan", notes: "Didukung sistem informasi utama, namun belum memiliki akses ke sistem pendukung. Aplikasi mobile baru terintegrasi sebagian." },
    monitoring: { rating: "memadai", notes: "Weekly update dan pertemuan berkala dengan mitra kerja telah dilakukan secara konsisten." },
  },
  findings: [
    {
      id: "F001",
      title: "Pelaksanaan Tugas dan Fungsi Bidang Penghimpunan Masih Memerlukan Penguatan dalam Penerapan Prinsip Tata Kelola yang Baik",
      rating: "medium",
      cosoComponents: ["control_environment", "control_activities"],
      riskCategories: ["strategis", "operasional", "kepatuhan"],
      condition: "1) Ketidakselarasan Renstra 2022-2027 dengan program/RKAT/IKU BSC - Program tabungan dan cicilan setoran lunas belum tercantum di RKAT\n2) SOP hanya mencakup proses administrasi, belum prosedur tata laksana program\n3) Pertanggungjawaban kegiatan event tahunan belum mencakup dana non-RKAT (sponsorship Rp1,25M tidak tercatat)\n4) Tugas pengelolaan data peserta belum dimuat dalam SOTK",
      criteria: "Peraturan Internal No.3/2018 (GCG - Akuntabilitas & Transparansi); Pedoman Akuntansi Keuangan; Renstra 2022-2027; SOP 012 & 012A; Keputusan Rapat Pimpinan 12 Sep 2023",
      cause: "1) Belum ada mekanisme reviu penyelarasan Renstra secara berkala\n2) SOP belum dikinikan\n3) Belum ada ketentuan khusus penerimaan sponsorship\n4) Kurang koordinasi antar unit untuk SOTK",
      effect: "1) Kinerja tidak selaras dengan Renstra\n2) Pelaksanaan tugas tidak seragam\n3) Kurang transparansi laporan kegiatan (risiko perpajakan Rp1,25M)\n4) Pengelolaan data peserta kurang efektif",
      recommendation: "1) Reviu bersama penyelarasan Renstra dengan RKAT/IKU\n2) Susun SOP tata laksana program termasuk mekanisme sponsorship\n3) Penyesuaian SOTK dengan tugas pengelola data peserta",
      managementResponse: "Setuju diperlukan SOP. Tim Gabungan sudah dibentuk untuk kajian cicilan setoran.",
      targetDate: "2025-12-31",
      pic: "Deputi Bidang Penghimpunan",
      status: "open",
    },
    {
      id: "F002",
      title: "Pelaksanaan Program Penghimpunan Dana Belum Sepenuhnya Mempertimbangkan Prinsip Efektivitas",
      rating: "medium",
      cosoComponents: ["risk_assessment", "monitoring"],
      riskCategories: ["strategis", "kepatuhan"],
      condition: "1) Lokasi kegiatan sosialisasi belum berbasis analisis data - hanya 5 dari 33 LPJ mengacu kajian demografi\n2) Provinsi dengan pembatalan tinggi (2.740 peserta) belum ada program sosialisasi\n3) Kegiatan sosialisasi luar negeri Rp2,56M - kehadiran di bawah target (\u00b120 dan \u00b110 peserta)\n4) Double klaim cash referral 17 kasus senilai Rp1.700.000",
      criteria: "Renstra - peningkatan pertumbuhan pendaftaran; SOP 012A poin 1.b & 3; IKU 2024 (target 300 rekening baru); Peraturan Internal No.3/2018 (Responsibility & Kehati-hatian)",
      cause: "1) Perencanaan kegiatan sosialisasi kurang optimal - belum manfaatkan kajian demografi 2022\n2) Target peserta belum sesuai sasaran\n3) Kurang cermat dalam verifikasi klaim referral\n4) Belum ada sistem otomatis pengecekan klaim",
      effect: "1) Kegiatan sosialisasi kurang efektif - anggaran Rp3,23M belum optimal\n2) Hanya 2 dari 33 LPJ mencantumkan impact\n3) Pembayaran double klaim Rp1.700.000\n4) Meningkatkan risiko strategis dan kepatuhan",
      recommendation: "1) Buat dokumen perencanaan tahunan lokasi kegiatan sosialisasi berbasis data\n2) Evaluasi kegiatan via kuesioner dan pencantuman impact di LPJ\n3) Minta pengembalian double klaim dari mitra kerja\n4) Bangun sistem verifikasi klaim referral dengan Deputi TI",
      managementResponse: "Akan mendorong kuesioner via aplikasi mobile. Double klaim 0,04% dari total. Inisiasi otomasi klaim melalui sistem informasi.",
      targetDate: "2026-03-31",
      pic: "Deputi Bidang Penghimpunan",
      status: "open",
    },
  ],
  observations: [
    { id: "O001", title: "Aplikasi mobile belum terintegrasi end-to-end dengan seluruh mitra kerja", notes: "Fitur pembukaan rekening baru bisa dilakukan via 1 mitra (microsite). Mitra lain hanya direct link ke aplikasi masing-masing." },
    { id: "O002", title: "Perbedaan ruang lingkup kontrak vs invoice pada kegiatan event tahunan", notes: "Biaya lokasi dan publikasi dialihkan ke item lain tanpa dokumentasi formal perubahan spesifikasi." },
    { id: "O003", title: "Dokumentasi penerimaan sponsorship kegiatan event 2024 belum lengkap", notes: "Belum ada dokumen detil bukti penerimaan sponsorship baik fresh money maupun in-kind dari vendor." },
  ],
};

export default DEFAULT_STATE;
